"""add categories view

Revision ID: 0a42e6f4598b
Revises: e1e679c84ec1
Create Date: 2026-08-24 23:31:20.683820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a42e6f4598b'
down_revision: Union[str, None] = 'e1e679c84ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
 

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('month_transaction', sa.INTEGER(), sa.Computed('EXTRACT(month FROM transaction_date)', persisted=True), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('year_transaction', sa.INTEGER(), sa.Computed('EXTRACT(year FROM transaction_date)', persisted=True), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('day_transaction', sa.INTEGER(), sa.Computed('EXTRACT(day FROM transaction_date)', persisted=True), autoincrement=False, nullable=True))

    op.execute(
        """
        CREATE OR REPLACE VIEW categories_consolidated_view AS SELECT
            year_transaction,
            month_transaction,
            account_id,
            category,
            SUM(value)
        FROM transactions
        GROUP BY year_transaction, month_transaction, account_id, category 
        ORDER BY year_transaction DESC, month_transaction ASC, account_id ASC;
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'day_transaction')
    op.drop_column('transactions', 'year_transaction')
    op.drop_column('transactions', 'month_transaction')
    op.execute("DROP VIEW IF EXISTS categories_consolidated_view")
    # ### end Alembic commands ###
