"""initial schema

Revision ID: e1e679c84ec1
Revises: 
Create Date: 2026-08-18 22:14:25.052289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e1e679c84ec1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliable_banks',
    sa.Column('bank_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('bank_id')
    )
    op.bulk_insert(
        sa.table(
            'avaliable_banks',
            sa.column('bank_id', sa.Integer),
            sa.column('bank_name', sa.String),
        ), 
        [
        {'bank_id': 1, 'bank_name': 'Nubank'},
        {'bank_id': 2, 'bank_name': 'Inter'},
        {'bank_id': 3, 'bank_name': 'Itaú Unibanco'},
        {'bank_id': 4, 'bank_name': 'Bradesco'},
        {'bank_id': 5, 'bank_name': 'Banco BTG Pactual'},
        {'bank_id': 6, 'bank_name': 'Sicredi'},
        {'bank_id': 7, 'bank_name': 'Banco C6'},
        {'bank_id': 8, 'bank_name': 'Santander'},
        {'bank_id': 9, 'bank_name': 'Banco do Brasil'},
        {'bank_id': 10, 'bank_name': 'Banco Sofisa'},
        {'bank_id': 11, 'bank_name': 'Ágora'},
        ],
    )

    op.create_table('bank_accounts',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=100), nullable=False),
    sa.Column('start_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('-999000000000 < start_value AND start_value < 999000000000', name='check_start_value_limit'),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_name')
    ) 
    
    op.create_table('fixed_expenses',
    sa.Column('expense_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('due_day >= 1 AND due_day <= 31', name='check_due_day_range'),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tracking', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )

    op.execute("""
        CREATE OR REPLACE VIEW credit_installments_view AS
        SELECT
            t.transaction_id,
            t.account_id,
            t.description,
            t.category,
            t.transaction_date,
            t.value                                                      AS total_value,
            (t.details->>'installments')::int                            AS total_installments,
            gs.n                                                         AS installment_number,
            (t.details->>'first_payment')::date
                + make_interval(months => gs.n - 1)                      AS due_date,
            COALESCE((t.details->>'interest')::numeric, 0)               AS interest_rate,
            CASE
                WHEN COALESCE((t.details->>'interest')::numeric, 0) = 0 THEN
                    ROUND(t.value / (t.details->>'installments')::int, 4)
                ELSE
                    ROUND(
                        t.value
                        * ((t.details->>'interest')::numeric
                           * POWER(1 + (t.details->>'interest')::numeric,
                                   (t.details->>'installments')::int))
                        / (POWER(1 + (t.details->>'interest')::numeric,
                                 (t.details->>'installments')::int) - 1),
                        4)
            END                                                          AS installment_value
        FROM transactions t
        CROSS JOIN LATERAL generate_series(1, (t.details->>'installments')::int) AS gs(n)
        WHERE t.type = 'credit'
          AND t.details IS NOT NULL
          AND (t.details->>'installments') IS NOT NULL
          AND (t.details->>'first_payment') IS NOT NULL
    """)

    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS credit_installments_view")
    op.drop_table('transactions')
    op.drop_table('fixed_expenses')
    op.drop_table('bank_accounts')
    op.drop_table('avaliable_banks')
    # ### end Alembic commands ###
